title = "A Premier Ukrainian Law Firm"
baseurl = "https://static.vasko.ua"
languageCode = "en-us"
theme = "mygarland"
disableKinds = ["RSS"]

DefaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true

uglyURLs = false

[Languages]

[Languages.uk]
languageName = "Українська"
title = "Vasko"
weight = 1

[Languages.ru]
languageName = "Русский"
title = "Vasko"
weight = 2

[Languages.en]
languageName = "English"
title = "Vasko"
weight = 3


[privacy]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.speakerDeck]
disable = true

[privacy.x]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true
